CREATE TABLE  "E_BOOK" 
   (	"CALLNO" NUMBER, 
	"NAME" VARCHAR2(4000), 
	"AUTHOR" VARCHAR2(4000), 
	"PUBLISHER" VARCHAR2(4000), 
	"QUANTITY" NUMBER, 
	"ISSUED" NUMBER, 
	 CONSTRAINT "E_BOOK_PK" PRIMARY KEY ("CALLNO") ENABLE
   )
/
CREATE TABLE  "E_LIBRARIAN" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(4000), 
	"EMAIL" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(4000), 
	"MOBILE" NUMBER, 
	 CONSTRAINT "E_LIBRARIAN_PK" PRIMARY KEY ("ID") ENABLE
   )
/
Note: ID must be generated through sequence in E_LIBRARIAN table.

CREATE TABLE  "E_ISSUEBOOK" 
   (	"CALLNO" NUMBER NOT NULL ENABLE, 
	"STUDENTID" NUMBER NOT NULL ENABLE,  
	"ISSUEDDATE" DATE, 
	"ISSUEDURATION" NUMBER,
	"RETURNSTATUS" VARCHAR2(4000),
	CONSTRAINT "CALLNO_FK" FOREIGN KEY("CALLNO") REFERENCES E_BOOK("CALLNO") ENABLE,
	CONSTRAINT "STUDENTID_FK" FOREIGN KEY("STUDENTID") REFERENCES E_STUDENT("STUDENTID") ENABLE	
   )


CREATE TABLE "E_STUDENT"
(	"STUDENTID"	NUMBER,
	"STUDENTNAME" VARCHAR(200),
	"STUDENT_MAIL" VARCHAR(200),
	"STUDENTMOBILE" NUMBER,
	"STUDENT_UNAME" VARCHAR(200),
	"PASSWORD" VARCHAR(200),
	CONSTRAINT "STUDENTID_PK" PRIMARY KEY ("STUDENTID") ENABLE
)


